erDiagram
	language ||..|{ film : ""
	city ||..|{ address : ""
	country ||..|{ city : ""
	address ||..|{ customer : ""
	film ||..|{ filmactor : ""
	actor ||..|{ filmactor : ""
	film ||..|{ filmcategory : ""
	category ||..|{ filmcategory : ""
	film ||..|{ inventory : ""
	staff ||..|{ rental : ""
	inventory ||..|{ rental : ""
	customer ||..|{ rental : ""
	address ||..|{ staff : ""
	staff ||..|{ store : ""
	address ||..|{ store : ""
	staff ||..|{ payment : ""
	rental ||..|{ payment : ""
	customer ||..|{ payment : ""
