# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      working-directory: "./erd-explorer"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
        
      # Runs a single command using the runners shell
      - name: Install Npm Dependencies
        run: npm ci
        working-directory: ${{env.working-directory}}

      - name: compile and create vsix
        run: npm run package
        working-directory: ${{env.working-directory}}

      - name: Current NPM Package Version
        uses: justincy/npm-version-action@2.1.0
        id: npm-version
        with:
          path: ${{env.working-directory}}
              
      - name: upload vsix as artifact
        uses: actions/upload-artifact@v1
        with:
          name: erd-explorer-${{steps.npm-version.outputs.version}}.vsix
          path: ${{env.working-directory}}/erd-explorer-${{steps.npm-version.outputs.version}}.vsix
